### PR TITLE
integrate vyper locators natively in uiveri5

### PR DESCRIPTION
**Pull request by gtreskas**
* Locator integrations

### CODE REVIEW

**Comment by gtreskas** [comment]
Merged changes from: https://github.com/SAP/ui5-uiveri5/pull/150/files

@tsaleksandrova : Thanks for the help, I think I integrated your changes in my forked version, you can close it if you like

**Comment by gtreskas** [comment]
still need to clean up and see how we can bring it forward

**Comment by maximnaidenov** [comment]
Can you please rebase over master HEAD ?

**Comment by gtreskas** [comment]
yes sorry I ll do that

**Pull request closed without merging**
