### PR TITLE
Added detailed screenshots to screenshot report

### PR DESCRIPTION
**Pull request by sebbi08**
In the Screenshort reporter when there is a remote image storage setup show the acc/ref and diff image in the reporter

### CODE REVIEW

**Comment by maximnaidenov** [comment]
Hi,
Seems you are using the visual testing profile ? Where do you store the images - implement your own storage backend ?. 
As for reporter, we have the HTML reporter that is intended for this specific usecase as we run some visual tests ourselfs. Maybe you can try it and then we could discuss if you really need this feature the in the screenshot reporter.

**Comment by sebbi08** [comment]
Hi,
yes we are and yes we implemented it on our onw.

Ok wasen expectin the thml report to have the screenshots in there 😂 but accually i like the look and feel of the screenshot reporter more than the html. And also the html reporter dos not show the Action screenshots.

Is it possible to implement an reporter on our own becuause i could not find a way how to setup the "name" property so that it is loding the custom reportet

**Comment by maximnaidenov** [comment]
It is unfortunate that you needed to implement this yourself, we have a java based app but we did not consider anyone to be interested and so did not open-sourced it. Another option is to use the localScreenshotProvider, it is intended for the usacase of storing the images in git. This should be a viable option if you have an integration test with an occasional screenshot comparison.
Third option is git LFS - at the time we implemented the providers, the git LFS was not available on gerrit/github/gitlab and so we were forced to implement our own strage but I would say it would be relatively simple to write a storage provider to store to git LFS. Then you get the management options for free and you can easily purge old or excessive screenshots.
The idea of the HTML report is to have an overview of all visual tests because in our setup they are pure "visual tests" e.g. we discourage having extensive logic, the test only drives individual controls to showcase all their visual states. So the actions are less important and so we miss them form the report to avoid clutter.
I will have a look at your changes and possibly merge. 
As for new reporter, of course, it is possible, can you please share some example of a custom reporter and we could help ?

**Comment by maximnaidenov** [comment]
sorry for the long delay in merging, will release a new version soon that will include this fix also.

**Pull request merged**
